version: "3.3"
services:
    image-previewer:
        image: sinuspower/image-previewer
        container_name: image-previewer
        volumes:
            - ${LOGS_DIR}:/root/logs
        ports:
            - "${IMAGE_PREVIEWER_PORT}:${IMAGE_PREVIEWER_PORT}"
        environment:
            - IMAGE_PREVIEWER_PORT=${IMAGE_PREVIEWER_PORT}
            - IMAGE_PREVIEWER_CACHE_SIZE=20
            - IMAGE_PREVIEWER_MIN_WIDTH=50
            - IMAGE_PREVIEWER_MIN_HEIGHT=50
            - IMAGE_PREVIEWER_MAX_WIDTH=2000
            - IMAGE_PREVIEWER_MAX_HEIGHT=2000
